### ISSUE TITLE
roadmap to v1

### ISSUE THREAD

**Issue by topliceanu** [topliceanu/schedule-drone#4]
- [ ] organize the module into two distinct pieces: 
  - scheduler process
  - rest api process for publishing scheduled tasks, use [mortimer](http://github.com/topliceanu/mortimer)
- [ ] get inspiration from other projects: 
  - [kala](https://github.com/ajvb/kala)
  - [dalga](https://github.com/cenkalti/dalga) written in Go and quite new
  - [rufus](https://github.com/jmettraux/rufus-scheduler)
  - [azure scheduler service](http://azure.microsoft.com/en-us/services/scheduler/)
  - [mandrill handles webhooks gracefully](http://help.mandrill.com/entries/22285907-What-happens-if-my-webhook-URL-is-down-or-can-t-accept-requests-) and [mandrill api for webhooks](
- [ ] add comments, generated docs, code coverage, examples, etc.https://mandrillapp.com/api/docs/webhooks.html)
- [ ] simplify current implementation, no need to extend event emitter
- [ ] support full configuration of webhooks, alternate urls, fallback urls, monitoring, etc.
- [ ] allow customization of endpoint requests. This should allow people to post on queues, etc. Support Amazon SQS and Azure Storage Queue. Support HTTP Basic Auth for outbount links 
- [ ] [nice to have] make it api-compatible with azure scheduler 
- [ ] maintain a job history, store the results for all the executed jobs
- [ ] [nice to have] add a ui for the scheduler-drone in angular.js
  - build a calendar view of the running jobs. see [angular-ui:calendar](http://angular-ui.github.io/ui-calendar/)
- [ ] find a way to bundle recurring jobs toghether, so they don't appear as being separated from each other
- [ ] syntax for a scheduler job, what it contains and how it translates to work [docs](http://msdn.microsoft.com/library/azure/dn528941.aspx): retry policy, http verb&url, what to do when there is an error, recurrance params, time of day, job state, outbound endpoint response, etc. 
- [ ] cli interface for the daemon process
- documentation on the azure scheduler http://msdn.microsoft.com/en-us/library/azure/dn479785.aspx
- [ ] you could have a recurrent request be performed with a certain periodicity, but not after a configured date.
- [ ] human readable cron intervals
- [ ] option to specify timezone when configuring a job!

Old and busted todos
- ~~use redis as a backend and especially it's `EXPIRE NOTIFY` feature~~
- ~~rest api and programatic api (only when embedded in node.js applications)~~
- ~~complete refactor, rewrite everything in coffeescript, use express.js for rest api, use mocha for testing~~

**Comment by topliceanu** [comment]
not going to implement redis backend for now

**Comment by topliceanu** [comment]
Works pretty much like ruby's [DelayedJob](https://devcenter.heroku.com/articles/delayed-job)
